### ISSUE TITLE
What fields should we import?

### ISSUE THREAD

**Issue by ajzeigert** [MaptimeBend/bend_buildings#1]
Current fields in `building_footprints2004_intlfeet.shp` and whether we should import them.

| Field name | Description | Import? | Corresponding OSM tag |
| --- | --- | --- | --- |
| `FID_` | Internal ID number | No | None |
| `ENTITY` | Geometry type description | No | None |
| `HANDLE` | Not sure, all values _NULL_ | No | None |
| `LAYER` | Seems to describe whether it's a mobile home, secondary structure, etc. Would need a proper key | Yes, if we can translate to useful OSM tags | TBA |
| `COLOR` | Not sure | No | None |
| `LINETYPE` | Another geometry description, all values CONTINUOUS | No | None |
| `ELEVATION` | Probably ground elevation? | Maybe, see below | [ele](http://wiki.openstreetmap.org/wiki/Key:ele) |
| `THICKNESS` | Not sure | No | None |
| `TEXT` | All values _NULL_ | No | None |

I'd also like to propose these additional fields, if we can acquire the corresponding data:

| Field name | Description | Source | Corresponding OSM tag |
| --- | --- | --- | --- |
| `height` | Height of structure | Derive from DOGAMI lidar | `height` [wiki](http://wiki.openstreetmap.org/wiki/Key:height) |
| `House_Number` | Address of building | Derive from Deschutes County data | `addr:housenumber` [wiki](https://wiki.openstreetmap.org/wiki/Key:addr) |
| `Street_Name` + `Street_Type` | Address of building | Derive from Deschutes County data | `addr:street` [wiki](https://wiki.openstreetmap.org/wiki/Key:addr) |

**Comment by ajzeigert** [comment]
I realize that buildings and addresses don't always have a 1:1 relationship. But I bet like 90% of buildings would only have one address associated with them.

**Comment by blairdgeo** [comment]
Nice work @ajzeigert!  FWIW - I would _**assume**_ the majority of the attribute columns are a carry over from the original CAD planimetric drawing.  The 'ENTITY' and 'LAYER' may provide some leverage to filter the buildings.

**Comment by blairdgeo** [comment]
🥇
